apiVersion: v1
kind: Service
metadata:
  name: better300-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8061
      protocol: TCP
  selector:
    app: better-300-chart
